export const EMAIL_REQUEST = "EMAIL_REQUEST";
export const EMAIL_SUCCESS = "EMAIL_SUCCESS";
export const EMAIL_FAIL = "EMAIL_FAIL";

export const ADMIN_EMAIL_REQUEST = "ADMIN_EMAIL_REQUEST";
export const ADMIN_EMAIL_SUCCESS = "ADMIN_EMAIL_SUCCESS";
export const ADMIN_EMAIL_FAIL = "ADMIN_EMAIL_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";